# Default values for prometheus-http-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: yevhenkalyna/prometheus_http_exporter
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.1.1"

# Prometheus HTTP Exporter configuration file.
config:
  publish_port: 8000 # [Optional] Serving port, here you can see your metrics, default 8000
  check_delay: 5 # [Optional] How often we should check enpoints, in seconds, default 5
  push_gateway: # [Optional] Prometheus Pushgateway configuration
    address: prometheus-pushgateway:9091 # Address of Prometheus Pushgateway
    job: prometheus_http_exporter # [Optional] Metric label
  targets: # List of targets to gather and check
  - pattern: ^api.* # Regular expresion which will find your Ingress Host
    path: /swagger-ui.html # Path to check in each finded Ingress Host
    follow_redirects: true # [Optional] Should we follow redirects, default True
    insecure_skip_verify: true # [Optional] Should we check secure connection or not, default False
    timeout: 5 # [Optional] Fail if can't connect to URL after N seconds, default 5

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
